### ISSUE TITLE
Please fix A12 device respring loop on iOS 12.4, which Jailbreak with Unc0ver.

### ISSUE THREAD

**Issue by Halo-Michael** [parrotgeek1/Globalize#1]
Seems it will make A12 device respring loop on iOS 12.4, Jailbreak with Unc0ver.

**Comment by iq860** [comment]
same issue just had to uninstall it, cant wait to get Facetime back 
thanx

**Comment by Halo-Michael** [comment]
I think the cause of the problem is not A12 but the substitute itself used by unc0ver.  The same situation is encountered when using unc0ver (using substitute) on iPhone 7 in iOS13.  With checkra1n (using substrate) everything works fine.

**Comment by Halo-Michael** [comment]
@parrotgeek1 Can you please explain if you know why?

**Comment by Halo-Michael** [comment]
Seems there have no /System/Library/Frameworks/MobileWiFi.framework/MobileWiFi (nor /System/Library/PriveteFrameworks/MobileWiFi.framework/MobileWiFi) or process named com.apple.MobileWiFi anymore. Because we don't have process named com.apple.MobileWiFi, so substitute can't work fine then make device respring loop.

**Comment by parrotgeek1** [comment]
This is incorrect. These files are missing because they are in the dyld shared cache. They are not there on disk in iOS 12 either, and the same method works.

**Comment by Halo-Michael** [comment]
> This is incorrect. These files are missing because they are in the dyld shared cache. They are not there on disk in iOS 12 either, and the same method works.

How about the progress "com.apple.MobileWiFi"?

**Comment by Halo-Michael** [comment]
And /System/Library/Frameworks/MobileWiFi.framework have already moved to /System/Library/PrivateFrameworks/MobileWiFi.framework/MobileWiFi since 12.x (or eariler?)

**Comment by zjw88282740** [comment]
just remove WAPIHook.dylib and WAPIHook.plist from the deb, everything works well

**Comment by parrotgeek1** [comment]
@zjw88282740 thank you for the hint, I have fixed this issue in v0.3

**Comment by Halo-Michael** [comment]
Well, can this be considered a "fix"?

**Comment by Halo-Michael** [comment]
@parrotgeek1 Sorry, that can’t fix the issues. Still need to disable wapihook on unc0ver. (With substrate still works fine)
