### ISSUE TITLE
ios14.3 is not supported

### ISSUE THREAD

**Issue by jackiejtr** [parrotgeek1/Globalize#10]
Is there any plan to continue update? thx

**Comment by Tintin-404** [comment]
I have the same issue

**Comment by Tintin-404** [comment]
> Is there any plan to continue update? thx

Hi, I tried to install the deb on iOS 14.3, remember don’t respiring, then ldrestart. It workers. I think you can try this operation.

**Comment by parrotgeek1** [comment]
In that case, this issue was caused by user error so I will close it. I'm
glad to hear it's still working. --

Ethan Nelson-Moore
