### ISSUE TITLE
Install from cydia/.dep is not working

### ISSUE THREAD

**Issue by iq860** [parrotgeek1/Globalize#2]
Installation of the packege from cydia from your official repo is not working
Even from filza and mssege attached
![579DE73E-02E4-474F-9604-F7660D8A5639](https://user-images.githubusercontent.com/15311677/67642986-0720a280-f92b-11e9-8844-8d3a32a508ac.png)
 shows up

**Comment by parrotgeek1** [comment]
The current version is 0.2.5; please refresh cydia

**Comment by iq860** [comment]
The error that u saw was for the 0.2.4 from filza
I get error 403 on Sileo

https://ibb.co/m6NVgqd

**Comment by parrotgeek1** [comment]
0.2.4 does not exist. It is removed from my server. Why are you trying to download it instead of the newest 0.2.5?

**Comment by iq860** [comment]
This error is from ur server 
The version is 0.2.5

**Comment by parrotgeek1** [comment]
I just fixed this, it was a problem with my server code. sorry
