### ISSUE TITLE
Should not display alert on installation finish

### ISSUE THREAD

**Issue by s-kk** [parrotgeek1/Globalize#5]
Hello!
I've read the latest commit and noticed the finishing action was changed from kill springboard to ```ldrestart```. Please also update the alert displayed on Cydia installation.

**Comment by parrotgeek1** [comment]
It is not possible to do this. Cydia only supports rebooting or killing springboard

**Comment by s-kk** [comment]
Sorry, I didn't read it through. I thought changes on theo configuration applies to Cydia post-installation.  
Anyway thanks for helping!
