### ISSUE TITLE
ios 13.4.1 facetime audio not working

### ISSUE THREAD

**Issue by antergone** [parrotgeek1/Globalize#9]
Facetime Audio for Chinese iPhone Models（iPhone 7）

Working:
ios 13.1.3
globalize: 0.2.5
About: MNGX2CH/A

Not Working
ios 13.4.1
globalize: 0.3.2
About: MNGX2CH/A

**Comment by parrotgeek1** [comment]
in the about screen on iOS 13.4.1 does it show MNGX2B/A? If it doesn't then Globalize isn't working at all.

**Comment by antergone** [comment]
> in the about screen on iOS 13.4.1 does it show MNGX2B/A? If it doesn't then Globalize isn't working at all.

No, it's always show MNGX2CH/A on iOS 13.4.1.

**Comment by antergone** [comment]
> in the about screen on iOS 13.4.1 does it show MNGX2B/A? If it doesn't then Globalize isn't working at all.

Test on iOS 13.1.3

globalize: 0.3.2
About: MNGW2X/A
facetime audio working

**Comment by parrotgeek1** [comment]
I can't reproduce this. It's working for me and others on 13.4.1 and 13.5.
